services:

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_DISABLE_CONTAINERS=
      - WATCHTOWER_SCHEDULE=${WATCHTOWER_SCHEDULE}
      - TZ=${GLOBAL_TIMEZONE}
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_INCLUDE_RESTARTING=false
      - WATCHTOWER_INCLUDE_STOPPED=false
      - WATCHTOWER_REVIVE_STOPPED=false
      - WATCHTOWER_TIMEOUT=30s
      - WATCHTOWER_NOTIFICATIONS=shoutrrr
      - WATCHTOWER_NOTIFICATION_URL=${WATCHTOWER_NOTIFICATION_URL}
    # You can remove the command section and all the apps listed under it to have Watchtower update all containers running in Docker on your server.
    command:
      - deunhealth
      - gluetun
      - jellyfin
      - jellyseerr
      - prowlarr
      - qbittorrent
      - radarr
      - sonarr
      - watchtower

  deunhealth:
    image: qmcgaw/deunhealth
    container_name: deunhealth
    network_mode: "none"
    environment:
      - LOG_LEVEL=info
      - HEALTH_SERVER_ADDRESS=127.0.0.1:9999
      - TZ=${GLOBAL_TIMEZONE}
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8080:8080 # qbittorrent web interface
      - 8989:8989 # sonarr
      - 7878:7878 # radarr
      - 9696:9696 # prowlarr
    volumes:
      - ${GLOBAL_DOCKERROOTPATH}/gluetun:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=nordvpn
      - VPN_TYPE=openvpn
      - OPENVPN_USER=${VPN_USER}
      - OPENVPN_PASSWORD=${VPN_PASSWORD}
      - SERVER_COUNTRIES=Canada
      - HEALTH_VPN_DURATION_INITIAL=120s
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    labels:
      deunhealth.restart.on.unhealthy: ${DEUNHEALTH_RESTART}
    environment:
      - PUID=${GLOBAL_PUID}
      - PGID=${GLOBAL_PGID}
      - TZ=${GLOBAL_TIMEZONE}
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - ${GLOBAL_DOCKERROOTPATH}/qbittorrent:/config
      - ${GLOBAL_MEDIAROOTPATH}:/data
      #- ${GLOBAL_MEDIA_SHOWS}:/data/Shows
      #- ${GLOBAL_MEDIA_MOVIES}:/data/Movies
      #- ${GLOBAL_MEDIA_ANIME}:/data/Anime
      #- ${GLOBAL_MEDIA_DOWNLOADS}:/data/Downloads
    network_mode: service:gluetun
    depends_on:
      - gluetun
      - deunhealth
    healthcheck:
        test: ping -c 1 www.google.com || exit 1
        interval: 60s
        retries: 3
        start_period: 20s
        timeout: 10s

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=${GLOBAL_PUID}
      - PGID=${GLOBAL_PGID}
      - TZ=${GLOBAL_TIMEZONE}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${GLOBAL_DOCKERROOTPATH}/prowlarr:/config
    restart: unless-stopped
    network_mode: service:gluetun
    depends_on:
      - gluetun
      - deunhealth
      - qbittorrent
    healthcheck:
        test: ping -c 1 www.google.com || exit 1
        interval: 60s
        retries: 3
        start_period: 20s
        timeout: 10s
    labels:
      deunhealth.restart.on.unhealthy: ${DEUNHEALTH_RESTART}

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    environment:
      - PUID=${GLOBAL_PUID}
      - PGID=${GLOBAL_PGID}
      - TZ=${GLOBAL_TIMEZONE}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${GLOBAL_DOCKERROOTPATH}/sonarr:/config
      - ${GLOBAL_MEDIAROOTPATH}:/data
      #- ${GLOBAL_MEDIA_SHOWS}:/data/Shows
      #- ${GLOBAL_MEDIA_MOVIES}:/data/Movies
      #- ${GLOBAL_MEDIA_ANIME}:/data/Anime
      #- ${GLOBAL_MEDIA_DOWNLOADS}:/data/Downloads
    network_mode: service:gluetun
    depends_on:
      - gluetun
      - deunhealth
      - qbittorrent
      - prowlarr
    healthcheck:
        test: ping -c 1 www.google.com || exit 1
        interval: 60s
        retries: 3
        start_period: 20s
        timeout: 10s
    labels:
      deunhealth.restart.on.unhealthy: ${DEUNHEALTH_RESTART}

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    environment:
      - PUID=${GLOBAL_PUID}
      - PGID=${GLOBAL_PGID}
      - TZ=${GLOBAL_TIMEZONE}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${GLOBAL_DOCKERROOTPATH}/radarr:/config
      - ${GLOBAL_MEDIAROOTPATH}:/data
      #- ${GLOBAL_MEDIA_SHOWS}:/data/Shows
      #- ${GLOBAL_MEDIA_MOVIES}:/data/Movies
      #- ${GLOBAL_MEDIA_ANIME}:/data/Anime
      #- ${GLOBAL_MEDIA_DOWNLOADS}:/data/Downloads
    network_mode: service:gluetun
    depends_on:
      - gluetun
      - deunhealth
      - qbittorrent
      - prowlarr
    healthcheck:
        test: ping -c 1 www.google.com || exit 1
        interval: 60s
        retries: 3
        start_period: 20s
        timeout: 10s
    labels:
      deunhealth.restart.on.unhealthy: ${DEUNHEALTH_RESTART}

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - PUID=${GLOBAL_PUID}
      - PGID=${GLOBAL_PGID}
      - TZ=${GLOBAL_TIMEZONE}
    volumes:
      - ${GLOBAL_DOCKERROOTPATH}/jellyseerr/config:/app/config
    restart: unless-stopped
    ports:
      - 5055:5055
    depends_on:
      - sonarr
      - radarr