services:

  deunhealth:
    image: qmcgaw/deunhealth:${VERSIONTAG_DEUNHEALTH}
    container_name: deunhealth
    restart: unless-stopped
    network_mode: "none"
    environment:
      - LOG_LEVEL=info
      - HEALTH_SERVER_ADDRESS=127.0.0.1:9999
      - TZ=${GLOBAL_TIMEZONE}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  gluetun:
    image: qmcgaw/gluetun:${VERSIONTAG_GLUETUN}
    container_name: gluetun
    restart: unless-stopped
    networks: 
      - simplarr-stack_network
    cap_add:
      - NET_ADMIN
    ports:
      - 8080:8080   # qbittorrent web interface
      - 8191:8191   # flaresolverr
      - 8989:8989   # sonarr
      - 7878:7878   # radarr
      - 9696:9696   # prowlarr
    environment:
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER}
      - VPN_TYPE=openvpn
      - OPENVPN_USER=${VPN_USER}
      - OPENVPN_PASSWORD=${VPN_PASSWORD}
      - SERVER_COUNTRIES=${VPN_COUNTRY}
      - SERVER_REGIONS=${VPN_REGIONS}
      - HEALTH_VPN_DURATION_INITIAL=120s
    volumes:
      - ${GLOBAL_DOCKERROOTPATH}/gluetun:/gluetun
    devices:
      - /dev/net/tun:/dev/net/tun
    healthcheck:
        test: ping -c 1 www.google.com || exit 1
        interval: ${HEALTHCHECK_INTERVAL}
        retries: ${HEALTHCHECK_RETRIES}
        start_period: ${HEALTHCHECK_STARTPERIOD}
        timeout: ${HEALTHCHECK_TIMEOUT}
    labels:
      deunhealth.restart.on.unhealthy: ${DEUNHEALTH_RESTART}

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:${VERSIONTAG_FLARESOLVERR}
    container_name: flaresolverr
    restart: unless-stopped
    network_mode: service:gluetun
    environment:
      - TZ=${GLOBAL_TIMEZONE}
    volumes:
      - ${GLOBAL_DOCKERROOTPATH}/flaresolverr/config:/config
    healthcheck:
        test: ["CMD-SHELL", "curl -f -s https://www.google.com > /dev/null || exit 1"]
        interval: ${HEALTHCHECK_INTERVAL}
        retries: ${HEALTHCHECK_RETRIES}
        start_period: ${HEALTHCHECK_STARTPERIOD}
        timeout: ${HEALTHCHECK_TIMEOUT}
    labels:
      deunhealth.restart.on.unhealthy: ${DEUNHEALTH_RESTART}

  gotify:
    image: gotify/server:${VERSIONTAG_GOTIFY}
    container_name: gotify
    restart: unless-stopped
    networks: 
      - simplarr-stack_network
    ports:
      - 8880:8880
    environment:
      - GOTIFY_DEFAULTUSER_PASS=${GOTIFY_DEFAULTUSER_PASS}
      - PUID=${GLOBAL_PUID}
      - PGID=${GLOBAL_PGID}
      - TZ=${GLOBAL_TIMEZONE}
      - GOTIFY_SERVER_PORT=8880
    volumes:
      - ${GLOBAL_DOCKERROOTPATH}/gotify/gotify_data:/app/data

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:${VERSIONTAG_PROWLARR}
    container_name: prowlarr
    restart: unless-stopped
    network_mode: service:gluetun
    environment:
      - PUID=${GLOBAL_PUID}
      - PGID=${GLOBAL_PGID}
      - TZ=${GLOBAL_TIMEZONE}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${GLOBAL_DOCKERROOTPATH}/prowlarr:/config
    healthcheck:
        test: ping -c 1 www.google.com || exit 1
        interval: ${HEALTHCHECK_INTERVAL}
        retries: ${HEALTHCHECK_RETRIES}
        start_period: ${HEALTHCHECK_STARTPERIOD}
        timeout: ${HEALTHCHECK_TIMEOUT}
    labels:
      deunhealth.restart.on.unhealthy: ${DEUNHEALTH_RESTART}

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:${VERSIONTAG_QBITTORRENT}
    container_name: qbittorrent
    restart: unless-stopped
    network_mode: service:gluetun
    environment:
      - PUID=${GLOBAL_PUID}
      - PGID=${GLOBAL_PGID}
      - TZ=${GLOBAL_TIMEZONE}
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - ${GLOBAL_DOCKERROOTPATH}/qbittorrent:/config
      - ${GLOBAL_MEDIA_SHOWS}:/data/Shows
      - ${GLOBAL_MEDIA_MOVIES}:/data/Movies
      - ${GLOBAL_MEDIA_ANIME}:/data/Anime
      - ${GLOBAL_MEDIA_DOWNLOADS}:/data/Downloads
    healthcheck:
        test: ping -c 1 www.google.com || exit 1
        interval: ${HEALTHCHECK_INTERVAL}
        retries: ${HEALTHCHECK_RETRIES}
        start_period: ${HEALTHCHECK_STARTPERIOD}
        timeout: ${HEALTHCHECK_TIMEOUT}
    labels:
      deunhealth.restart.on.unhealthy: ${DEUNHEALTH_RESTART}

  sonarr:
    image: lscr.io/linuxserver/sonarr:${VERSIONTAG_SONARR}
    container_name: sonarr
    restart: unless-stopped
    network_mode: service:gluetun
    environment:
      - PUID=${GLOBAL_PUID}
      - PGID=${GLOBAL_PGID}
      - TZ=${GLOBAL_TIMEZONE}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${GLOBAL_DOCKERROOTPATH}/sonarr:/config
      - ${GLOBAL_MEDIA_SHOWS}:/data/Shows
      - ${GLOBAL_MEDIA_MOVIES}:/data/Movies
      - ${GLOBAL_MEDIA_ANIME}:/data/Anime
      - ${GLOBAL_MEDIA_DOWNLOADS}:/data/Downloads
    healthcheck:
        test: ping -c 1 www.google.com || exit 1
        interval: ${HEALTHCHECK_INTERVAL}
        retries: ${HEALTHCHECK_RETRIES}
        start_period: ${HEALTHCHECK_STARTPERIOD}
        timeout: ${HEALTHCHECK_TIMEOUT}
    labels:
      deunhealth.restart.on.unhealthy: ${DEUNHEALTH_RESTART}

  radarr:
    image: lscr.io/linuxserver/radarr:${VERSIONTAG_RADARR}
    container_name: radarr
    restart: unless-stopped
    network_mode: service:gluetun
    environment:
      - PUID=${GLOBAL_PUID}
      - PGID=${GLOBAL_PGID}
      - TZ=${GLOBAL_TIMEZONE}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${GLOBAL_DOCKERROOTPATH}/radarr:/config
      - ${GLOBAL_MEDIA_SHOWS}:/data/Shows
      - ${GLOBAL_MEDIA_MOVIES}:/data/Movies
      - ${GLOBAL_MEDIA_ANIME}:/data/Anime
      - ${GLOBAL_MEDIA_DOWNLOADS}:/data/Downloads
    healthcheck:
        test: ping -c 1 www.google.com || exit 1
        interval: ${HEALTHCHECK_INTERVAL}
        retries: ${HEALTHCHECK_RETRIES}
        start_period: ${HEALTHCHECK_STARTPERIOD}
        timeout: ${HEALTHCHECK_TIMEOUT}
    labels:
      deunhealth.restart.on.unhealthy: ${DEUNHEALTH_RESTART}

  seerr:
    image: ghcr.io/seerr-team/seerr:${VERSIONTAG_SEERR}
    container_name: seerr
    restart: unless-stopped
    networks: 
      - simplarr-stack_network
    ports:
      - 5055:5055
    environment:
      - PUID=${GLOBAL_PUID}
      - PGID=${GLOBAL_PGID}
      - TZ=${GLOBAL_TIMEZONE}
    volumes:
      - ${GLOBAL_DOCKERROOTPATH}/seerr/config:/app/config

  cleanuparr:
    image: ghcr.io/cleanuparr/cleanuparr:${VERSIONTAG_CLEANUPARR}
    container_name: cleanuparr
    restart: unless-stopped
    networks: 
      - simplarr-stack_network
    ports:
      - 11011:11011
    environment:
      - PORT=11011
      - BASE_PATH=
      - PUID=${GLOBAL_PUID}
      - PGID=${GLOBAL_PGID}
      - TZ=${GLOBAL_TIMEZONE}
      - UMASK=022
    volumes:
      - ${GLOBAL_DOCKERROOTPATH}/cleanuparr/config:/config

  maintainerr:
    image: ghcr.io/maintainerr/maintainerr:${VERSIONTAG_MAINTAINERR}
    container_name: maintainerr
    restart: unless-stopped
    networks: 
      - simplarr-stack_network
    restart: unless-stopped
    ports:
      - 6246:6246
    volumes:
      - ${GLOBAL_DOCKERROOTPATH}/maintainerr/data:/opt/data
    environment:
      - TZ=${GLOBAL_TIMEZONE}

networks:
  simplarr-stack_network:
    name: ${SIMPLARR_NETWORK}
    driver: bridge